name: .NET

on:
  push:
    branches: 
    - feature/*
    - fix/*
    - refactor/*
    - main
  pull_request:
    branches:
    - feature/*
    - fix/*
    - refactor/*
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Engine
      run: dotnet build Engine --no-restore
    - name: Build Tests
      run: dotnet build Tests --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
